import { InferEnum, InferKeyAsEnum } from "@/utils/inferEnum.js";

export const TestStatus = {
  REQUESTED: "REQUESTED",
  REQUEST_CANCELLED: "REQUEST_CANCELLED",
  REQUEST_DECLINED: "REQUEST_DECLINED",
  REQUEST_ACCEPTED: "REQUEST_ACCEPTED",
  PRODUCT_ORDERED: "PRODUCT_ORDERED",
  PRODUCT_RECEIVED: "PRODUCT_RECEIVED",
  PRODUCT_REVIEWED: "PRODUCT_REVIEWED",
  REVIEW_VALIDATED: "REVIEW_VALIDATED",
  REVIEW_REFUSED: "REVIEW_REFUSED",
  MONEY_SENT: "MONEY_SENT",
  MONEY_RECEIVED: "MONEY_RECEIVED",
  TEST_CANCELLED: "TEST_CANCELLED",
} as const;
export type TestStatus = InferEnum<typeof TestStatus>;

export const GLOBAL_TEST_STATUSES: Record<string, Array<TestStatus>> = {
  REQUESTED: [TestStatus.REQUESTED, TestStatus.REQUEST_CANCELLED],
  PROCESSING: [
    TestStatus.REQUEST_ACCEPTED,
    TestStatus.PRODUCT_ORDERED,
    TestStatus.PRODUCT_RECEIVED,
    TestStatus.PRODUCT_REVIEWED,
    TestStatus.REVIEW_VALIDATED,
    TestStatus.MONEY_SENT,
  ],
  COMPLETED: [TestStatus.MONEY_RECEIVED],
  CANCELLED: [TestStatus.REVIEW_REFUSED, TestStatus.TEST_CANCELLED],
} as const;

export type GlobalTestStatus = InferKeyAsEnum<typeof GLOBAL_TEST_STATUSES>;
