require("dotenv").config();

const configs = {
  MONGODB_URI: process.env.MONGODB_URI,
  MONGO_LOCAL_URL: process.env.MONGO_LOCAL_URL,
  JWT_KEY: process.env.JWT_KEY,
  PORT: process.env.PORT,
  FRONTEND_URL: process.env.FRONTEND_URL,
  FRONTEND_LOCAL_URL: process.env.FRONTEND_LOCAL_URL,
  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
  PAYPAL_CLIENT_ID: process.env.PAYPAL_CLIENT_ID,
  PAYPAL_CLIENT_SECRET: process.env.PAYPAL_CLIENT_SECRET,
  PAYPAL_WEBHOOK_ID: process.env.PAYPAL_WEBHOOK_ID,
  PAYPAL_WEBHOOK_SECRET: process.env.PAYPAL_WEBHOOK_SECRET,
  AMAZON_ID: process.env.AMAZON_ID,
  AMAZON_SECRET: process.env.AMAZON_SECRET,
  AMAZON_BUCKET: process.env.AMAZON_BUCKET,
  AMAZON_REGION: process.env.AMAZON_REGION,
  AMAZON_URL: process.env.AMAZON_URL,
  AMAZON_PARTNER_ID: process.env.AMAZON_PARTNER_ID,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  FACEBOOK_CLIENT_ID: process.env.FACEBOOK_CLIENT_ID,
  FACEBOOK_CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET,
  FACEBOOK_CALLBACK_URL: process.env.FACEBOOK_CALLBACK_URL,
  FROM_MAIL_ADDRESS: process.env.FROM_MAIL_ADDRESS,
};

module.exports = configs;
